name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa uma vez por dia

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: BorgesGh
          outputs: |
            dist/github-contribution-grid-snake.svg

      - uses: actions/upload-artifact@v3
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg

      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist

      - uses: actions/deploy-pages@v1
